spring:
  application:
    name: springboot-deployment

server:
  port: ${PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    prometheus:
      enabled: true


